### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1Map** [numtel/meteor-pg-leaderboard#2]
I get the following error when running this example.

```
=> App running at: http://localhost:3000/
W20151001-01:35:06.265(2)? (STDERR) 
W20151001-01:35:06.266(2)? (STDERR) /home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg-live-select/index.js:366
W20151001-01:35:06.266(2)? (STDERR)       if('Plans' in node) found = found.concat(nodeWalker(node['Plans']));
W20151001-01:35:06.266(2)? (STDERR)                     ^
W20151001-01:35:06.266(2)? (STDERR) TypeError: Cannot use 'in' operator to search for 'Plans' in undefined
W20151001-01:35:06.266(2)? (STDERR)     at checkNode (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg-live-select/index.js:366:21)
W20151001-01:35:06.266(2)? (STDERR)     at nodeWalker (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg-live-select/index.js:371:10)
W20151001-01:35:06.267(2)? (STDERR)     at [object Object].callback (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg-live-select/index.js:382:29)
W20151001-01:35:06.267(2)? (STDERR)     at [object Object].Query.handleReadyForQuery (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg/lib/query.js:80:10)
W20151001-01:35:06.267(2)? (STDERR)     at [object Object].<anonymous> (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg/lib/client.js:158:19)
W20151001-01:35:06.267(2)? (STDERR)     at [object Object].emit (events.js:117:20)
W20151001-01:35:06.267(2)? (STDERR)     at Socket.<anonymous> (/home/schalk/.meteor/packages/numtel_pg/.1.0.1.1lwqc47++os+web.browser+web.cordova/npm/node_modules/pg/lib/connection.js:109:12)
W20151001-01:35:06.267(2)? (STDERR)     at Socket.emit (events.js:95:17)
W20151001-01:35:06.267(2)? (STDERR)     at Socket.<anonymous> (_stream_readable.js:765:14)
W20151001-01:35:06.267(2)? (STDERR)     at Socket.emit (events.js:92:17)
```

Can this be due to the fact that I am using Postgresql 9.1 ?

**Comment by numtel** [comment]
Possibly. Postgres 9.3+ is required.

**Comment by snubydev** [comment]
Hi, thnx for the example,
but there is a problem with concurrency. If several clients try to update data, they don't display the right value, but only initial value in session.
